version: '3.8'

networks:
  default:
    name: api-store

services:
  app:
    container_name: app
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    env_file: .env

  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql